### ISSUE TITLE
Add JSON support to API

### ISSUE THREAD

**Issue by Jaykul** [naushniki/qamail#2]

**Comment by naushniki** [comment]
Hi!
Currently, only XML is supported. I can implement JSON, if this is crucial for you.

**Comment by Jaykul** [comment]
What would it take? I mean, I have a team at work that's been playing with this and someone asked me for help writing code to check the email via the REST API instead of selenium automation -- but it's ultimately not my job. 

However, I might be willing to help plug in [Sinatra json](http://sinatrarb.com/contrib/json.html) if you think it's that simple ;-)

**Comment by naushniki** [comment]
This is a little bit more complicated than just plugging in a serializer. I will add JSON support to the API, but I'm busy now. I hope to do this on the next weekend. In the meantime, you might want to try another solution, which is to convert xml to json on the client side. QAMail front end does this using [x2js](https://github.com/abdmob/x2js). The code is as simple as it gets:
```
var parse = function(xml) {
    parser = new X2JS();
    return parser.xml_str2json(xml);
};
```

**Comment by naushniki** [comment]
JSON serialization is added to the API. To use JSON simply add path parameter format=json to any query.
